name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x to build
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run webpack:prod
    - name: Deploy
      run: git add dist -f && git commit -m "Deploy from Github Actions"
    - run: git subtree push --prefix dist origin gh-pages